site_name: Documentation EIG
site_url: https://entrepreneur-interet-general.github.io/
nav:
  - Programme EIG:
    - Les enjeux: enjeux.md
    - Les valeurs: valeurs.md
    - Les rôles: roles.md
    - L'approche: approche.md
    - Les dispositifs: dispositifs.md
    - Les services: services.md
    - Les indicateurs: indicateurs.md
    - L'écosystème: ecosysteme.md

  - Ressources utiles:
    - L'accessibilité numérique : accessibilite.md
    - Les algorithmes publics: algorithmes.md
    - Les canaux de communication: communication.md
    - Le design: design.md
    - La documentation: documentation.md
    - L'écriture inclusive: ecriture-inclusive.md
    - L'intégration des EIG: integration.md
    - Les licences libres: licences-libres.md
    - L'ouverture des données: open-data.md
    - L'ouverture des codes sources: open-source.md
    - Le prototypage: prototyper.md
    - La sécurité: securite.md
    - Le télétravail: travailler-distance.md

theme: 
  name: material
  logo: images/logo_blanc.png
  language: fr 
  favicon: images/favicon.png